### ISSUE TITLE
Kresman not able to download cache from core

### ISSUE THREAD

**Issue by robcza** [Elctro/Sink#11]
One particular deployment has an issue while downloading cache from core
```
2018-08-10 11:08:39,939 [17-4] FATAL [Kres.Man.CoreClient.?] - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kres.Man.CoreClient.GetCoreCacheLinux() in /app/CoreClient.cs:line 140
   at Kres.Man.CoreClient.ThreadProc() in /app/CoreClient.cs:line 33
```
Any idea what could be the issue?

**Comment by robcza** [comment]
It seems like a regular connection timeout, but it should be clearly stated in the log.
